apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  ports:
   - port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
    service: udagram-api-feed